[project]
name = "open-trustless-rewards"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.ft]
path = "contracts/ft.clar"

[contracts.ft-trait]
path = "contracts/ft-trait.clar"

[contracts.nft]
path = "contracts/nft.clar"

[contracts.nft-trait]
path = "contracts/nft-trait.clar"

[contracts.trustless-rewards]
path = "contracts/trustless-rewards.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
